# Generated by Django 2.2.7 on 2019-11-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_imgride'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
    ]
