# Generated by Django 2.2.7 on 2019-11-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191130_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgRide',
            field=models.ImageField(blank=True, upload_to='rate-my-ride'),
        ),
    ]
