# Generated by Django 2.2.7 on 2019-11-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191130_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgRide',
            field=models.ImageField(upload_to='rate-my-ride'),
        ),
    ]
