# Generated by Django 2.2.7 on 2019-11-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191130_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgRide',
            field=models.ImageField(blank=True, upload_to='rate-my-ride'),
        ),
    ]
