# Generated by Django 3.0 on 2020-01-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rate',
            table='post_rating',
        ),
    ]
