# Generated by Django 3.0 on 2019-12-19 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191219_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='main.Post'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
