# Generated by Django 3.0 on 2020-01-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200116_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Post'),
        ),
    ]
